# Shadowrocket: optimized
[General]
private-ip-answer = true
ipv6 = true
bypass-system = true
udp-policy-not-supported-behaviour = REJECT
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com
tun-excluded-routes = 239.255.255.250/32
dns-server = https://1.1.1.1/dns-query, https://8.8.8.8/dns-query

[Proxy]
# 此处留空，请通过小火箭扫描或订阅添加节点

[Proxy Group]
# 核心业务策略组
🧠 AI = select, 🇺🇸 美国节点, 所有-自动, 所有-手动, REJECT
▶️ MEDIA = select, 🇺🇸 美国节点, 所有-自动, 所有-手动, REJECT
🌍 国外 = select, 所有-自动, 所有-手动, REJECT
🇨🇳 国内 = select, DIRECT

# 国家自动分组
🇺🇸 美国节点 = url-test, policy-regex-filter=(🇺🇸|US|美国), url=http://www.gstatic.com/generate_204, interval=60
所有-自动 = url-test, policy-regex-filter=.*, url=http://www.gstatic.com/generate_204, interval=60
所有-手动 = select, policy-regex-filter=.*

# 可按需开启
# 🇸🇬 新加坡节点 = url-test, policy-regex-filter=(🇸🇬|SG|新加坡), url=http://www.gstatic.com/generate_204, interval=60
# 🇯🇵 日本节点 = url-test, policy-regex-filter=(🇯🇵|JP|日本), url=http://www.gstatic.com/generate_204, interval=60
# 🇰🇷 韩国节点 = url-test, policy-regex-filter=(🇰🇷|KR|韩国), url=http://www.gstatic.com/generate_204, interval=60
# 🇩🇪 德国节点 = url-test, policy-regex-filter=(🇩🇪|DE|德国), url=http://www.gstatic.com/generate_204, interval=60

[Rule]
RULE-SET,https://raw.githubusercontent.com/yaoqufeng/clash/refs/heads/main/Ai.list,🧠 AI
RULE-SET,https://raw.githubusercontent.com/yaoqufeng/clash/refs/heads/main/China.list,🇨🇳 国内
RULE-SET,https://raw.githubusercontent.com/yaoqufeng/clash/refs/heads/main/Media.list,▶️ MEDIA
RULE-SET,https://raw.githubusercontent.com/yaoqufeng/clash/refs/heads/main/Internet.list,🌍 国外

# 国内兜底
GEOIP,CN,🇨🇳 国内

# 未命中规则的流量默认走国外代理
FINAL,🌍 国外
