;1、域名组
ruleset=🌍 国外,https://raw.githubusercontent.com/yaoqufeng/clash/refs/heads/main/Proxy.list
ruleset=➡️ 国内,[]FINAL

;2、策略组（域名组-节点组）
custom_proxy_group=🌍 国外`select`[]DIRECT`[]所有-自动`[]美国-自动`[]其他-自动`[]REJECT
custom_proxy_group=➡️ 国内`select`[]DIRECT`[]所有-自动`[]美国-自动`[]其他-自动`[]REJECT

;3、节点组
custom_proxy_group=所有-自动`url-test`.*`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=美国-自动`url-test`(san jose|chicago|US|🇺🇸|United States)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=其他-自动`url-test`(Argo|vmess)`http://www.gstatic.com/generate_204`60,150

;4、启用规则集
enable_rule_generator=true
overwrite_original_rules=true
